### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by Testo-CTF** [baduker/LinkedIn_Learning_Downloader#1]
video_downloader.py 
2019-10-12 14:06:57,272 DEBUG    Using selector: EpollSelector
2019-10-12 14:06:57,273 INFO     [*] -------------Login------------
2019-10-12 14:06:57,273 INFO     *********
2019-10-12 14:06:57,273 INFO     *********
2019-10-12 14:06:57,273 INFO     [*] Login step 1 - Getting CSRF token...
2019-10-12 14:06:58,249 DEBUG    [*] CSRF: 8d97155a-834d-47f3-888f-e176d32ad1b6
2019-10-12 14:06:58,249 INFO     [*] Login step 1 - Done
2019-10-12 14:06:58,249 INFO     [*] Login step 2 - Logging In...
2019-10-12 14:06:59,248 INFO     [*] Login step 2 - Done
2019-10-12 14:06:59,248 INFO     [*] -------------Done-------------
2019-10-12 14:06:59,248 INFO     [*] --------Fetching Cours--------
Traceback (most recent call last):
  File "linkedin_video_downloader.py", line 281, in <module>
    loop.run_until_complete(process())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "linkedin_video_downloader.py", line 269, in process
    await fetch_courses()
  File "linkedin_video_downloader.py", line 133, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "linkedin_video_downloader.py", line 145, in fetch_course
    course = build_course(data['elements'][0])
KeyError: 'elements'
2019-10-12 14:07:00,049 ERROR    Unclosed connection
client_connection: Connection<ConnectionKey(host='www.linkedin.com', port=443, is_ssl=True, ssl=False, proxy=None, proxy_auth=None, proxy_headers_hash=-6905066090234145201)>

**Comment by baduker** [comment]
Make sure you have access to https://www.linkedin.com/learning/me?trk=nav_neptune_learning and double check your credentials.

**Comment by Testo-CTF** [comment]
yup i have access and my credentials 100% right 

as shown in the logs i send ,, i had already checkin - the error starts when fetching course 

2019-10-12 14:06:58,249 INFO [] Login step 2 - Logging In...
2019-10-12 14:06:59,248 INFO [] Login step 2 - Done

**Comment by Testo-CTF** [comment]
i put my full email in username field

is that ok ? 

that how i login to linkedin !

**Comment by Testo-CTF** [comment]
2019-10-13 08:45:38,060 INFO     [~] Fetching course 'GitHub Essential Training' Chapter no. 7 Video no. 3              2019-10-13 08:45:38,060 INFO     [~] Fetching course 'GitHub Essential Training' Chapter no. 7 Video no. 4              2019-10-13 08:45:38,060 INFO     [~] Fetching course 'GitHub Essential Training' Chapter no. 7 Video no. 5              2019-10-13 08:45:38,060 INFO     [~] Fetching course 'GitHub Essential Training' Chapter no. 7 Video no. 6              2019-10-13 08:45:38,070 INFO     [~] Fetching course 'GitHub Essential Training' Chapter no. 8 Video no. 1              Traceback (most recent call last):                                                                                        File ".\linkedin_video_downloader.py", line 281, in <module>                                                              loop.run_until_complete(process())                                                                                    File "C:\Users\mabdo\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 579, in run_until_complete                                                                                                                          return future.result()                                                                                                File ".\linkedin_video_downloader.py", line 269, in process                                                               await fetch_courses()                                                                                                 File ".\linkedin_video_downloader.py", line 133, in fetch_courses                                                         return await asyncio.gather(*map(fetch_course, COURSES))                                                              File ".\linkedin_video_downloader.py", line 146, in fetch_course                                                          await fetch_chapters(course)                                                                                          File ".\linkedin_video_downloader.py", line 162, in fetch_chapters                                                        fetch_chapter(course, chapter) for chapter in course.chapters))                                                       File ".\linkedin_video_downloader.py", line 198, in fetch_video                                                           video_url = data['elements'][0]['selectedVideo']['url']['progressiveUrl']                                           KeyError: 'url'

**Comment by baduker** [comment]
I've checked the course and it downloads without any problems. So the script should be fine. So I guess you problems might be related to your network. Also, if you get KeyError: 'elements' then the json that's being requested is not returned properly. Try rerunning the script or use a proxy.

**Comment by Testo-CTF** [comment]
i've tried 3 diffiernt networks ,,, and tried wired and wireless

and tried with proxy and without proxy 

and i've tried alot of slugs 

all what i get is ( folders with name of chapters but with no videos inside )

**Comment by baduker** [comment]
This is really strange. What system are you running the script on? Did you make sure the script has permission to write to your local disk?

**Comment by Testo-CTF** [comment]
and yeah i forgot to tell you :) 

i used it on linux ( Debian ) and windows 10 

as a root and administrator 

all the same result 
( folders with name of chapters but with no videos inside )

**Comment by baduker** [comment]
Honestly, I have no idea why is that. I've run the script on three virtual machines (Debian, Arch, and Windows) and it works fine. Have you modified the script in any way?

**Comment by Testo-CTF** [comment]
nope i just modify the config file to add the slug and the email address.... etc
